appname: "xonlist"
behind_proxy: 1
charset: "UTF-8"
desc: "XonList - Gameserver list for Xonotic. Servers, players, scores & more - Find Xonotic servers to play on."
domain: "xonotic.lifeisabug.com"
engines:
  template:
    template_autoFilter:
      AUTO_FILTER: "html_entity"
      COMPILE_DIR: "/tmp/tcc"
      COMPILE_EXT: ".tcc"
      POST_CHOMP: 2
      PRE_CHOMP: 2
      end_tag: "%]"
      start_tag: "[%"
environment: "production"
filedir: "/srv/www/xonotic.lifeisabug.com/app/files"
geodb: "/home/k/GeoLite2-City.mmdb"
template: "template_autoFilter"
title: "XonList - Xonotic Server List"
